### ISSUE TITLE
EIP-AuRa: Checklist before getting started

### ISSUE THREAD

**Issue by 5chdn** [goerli/eips-aura-spec#1]
- [x] create EIP for AuRa PoA from temlate (see EIP-X.md)
- [x] review the Clique PoA EIP-225, see https://github.com/ethereum/EIPs/issues/225
- [x] review the AuRa spec on Parity wiki https://wiki.parity.io/Aura.html
- [ ] request EIP number from upstream
